import os

# os.rename('task2.txt', 'text_file.txt')
# os.replace('task1.txt', r'/Users/artemmikulich/Desktop/myfreedom_offline_online/lesson_14_files/homework/homework.txt')
# print(f'путь текущей дериктории {os.getcwd()}')
# os.chdir('..')
# print(f'путь текущей дериктории {os.getcwd()}')
# os.chdir('homework')
# print(f'путь текущей дериктории {os.getcwd()}')
# os.chdir('..')
# os.chdir('class_materials')
# print(f'путь текущей дериктории {os.getcwd()}')
# os.remove(r'/Users/artemmikulich/Desktop/myfreedom_offline_online/lesson_14_files/homework/test.txt')
# os.mkdir('folder1')
# os.makedirs('folder2/folder3/folder4')
# os.rmdir('folder1')
# os.removedirs('folder2/folder3/folder4')
# os.mkdir('folder1')
# os.remove('folder1/test.txt')
# os.rmdir('folder1')
